// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetServiceClient interface {
	SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHellloServerStreaming(ctx context.Context, in *NameList, opts ...grpc.CallOption) (GreetService_SayHellloServerStreamingClient, error)
	SayHellloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHellloClientStreamingClient, error)
	SayHellloBiderctionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHellloBiderctionalStreamingClient, error)
}

type greetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetServiceClient(cc grpc.ClientConnInterface) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) SayHello(ctx context.Context, in *NoParam, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greet_service.GreetService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) SayHellloServerStreaming(ctx context.Context, in *NameList, opts ...grpc.CallOption) (GreetService_SayHellloServerStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[0], "/greet_service.GreetService/SayHellloServerStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHellloServerStreamingClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_SayHellloServerStreamingClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSayHellloServerStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHellloServerStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SayHellloClientStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHellloClientStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[1], "/greet_service.GreetService/SayHellloClientStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHellloClientStreamingClient{stream}
	return x, nil
}

type GreetService_SayHellloClientStreamingClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*MessageList, error)
	grpc.ClientStream
}

type greetServiceSayHellloClientStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHellloClientStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSayHellloClientStreamingClient) CloseAndRecv() (*MessageList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(MessageList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) SayHellloBiderctionalStreaming(ctx context.Context, opts ...grpc.CallOption) (GreetService_SayHellloBiderctionalStreamingClient, error) {
	stream, err := c.cc.NewStream(ctx, &GreetService_ServiceDesc.Streams[2], "/greet_service.GreetService/SayHellloBiderctionalStreaming", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceSayHellloBiderctionalStreamingClient{stream}
	return x, nil
}

type GreetService_SayHellloBiderctionalStreamingClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServiceSayHellloBiderctionalStreamingClient struct {
	grpc.ClientStream
}

func (x *greetServiceSayHellloBiderctionalStreamingClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceSayHellloBiderctionalStreamingClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServiceServer is the server API for GreetService service.
// All implementations must embed UnimplementedGreetServiceServer
// for forward compatibility
type GreetServiceServer interface {
	SayHello(context.Context, *NoParam) (*HelloResponse, error)
	SayHellloServerStreaming(*NameList, GreetService_SayHellloServerStreamingServer) error
	SayHellloClientStreaming(GreetService_SayHellloClientStreamingServer) error
	SayHellloBiderctionalStreaming(GreetService_SayHellloBiderctionalStreamingServer) error
	mustEmbedUnimplementedGreetServiceServer()
}

// UnimplementedGreetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (UnimplementedGreetServiceServer) SayHello(context.Context, *NoParam) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetServiceServer) SayHellloServerStreaming(*NameList, GreetService_SayHellloServerStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHellloServerStreaming not implemented")
}
func (UnimplementedGreetServiceServer) SayHellloClientStreaming(GreetService_SayHellloClientStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHellloClientStreaming not implemented")
}
func (UnimplementedGreetServiceServer) SayHellloBiderctionalStreaming(GreetService_SayHellloBiderctionalStreamingServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHellloBiderctionalStreaming not implemented")
}
func (UnimplementedGreetServiceServer) mustEmbedUnimplementedGreetServiceServer() {}

// UnsafeGreetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServiceServer will
// result in compilation errors.
type UnsafeGreetServiceServer interface {
	mustEmbedUnimplementedGreetServiceServer()
}

func RegisterGreetServiceServer(s grpc.ServiceRegistrar, srv GreetServiceServer) {
	s.RegisterService(&GreetService_ServiceDesc, srv)
}

func _GreetService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet_service.GreetService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).SayHello(ctx, req.(*NoParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_SayHellloServerStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NameList)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).SayHellloServerStreaming(m, &greetServiceSayHellloServerStreamingServer{stream})
}

type GreetService_SayHellloServerStreamingServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetServiceSayHellloServerStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHellloServerStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_SayHellloClientStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SayHellloClientStreaming(&greetServiceSayHellloClientStreamingServer{stream})
}

type GreetService_SayHellloClientStreamingServer interface {
	SendAndClose(*MessageList) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServiceSayHellloClientStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHellloClientStreamingServer) SendAndClose(m *MessageList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSayHellloClientStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_SayHellloBiderctionalStreaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).SayHellloBiderctionalStreaming(&greetServiceSayHellloBiderctionalStreamingServer{stream})
}

type GreetService_SayHellloBiderctionalStreamingServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greetServiceSayHellloBiderctionalStreamingServer struct {
	grpc.ServerStream
}

func (x *greetServiceSayHellloBiderctionalStreamingServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceSayHellloBiderctionalStreamingServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetService_ServiceDesc is the grpc.ServiceDesc for GreetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GreetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greet_service.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _GreetService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHellloServerStreaming",
			Handler:       _GreetService_SayHellloServerStreaming_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHellloClientStreaming",
			Handler:       _GreetService_SayHellloClientStreaming_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHellloBiderctionalStreaming",
			Handler:       _GreetService_SayHellloBiderctionalStreaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
